=== nerenererr/dtd-practice/registro_empleados/externo1.dtd
<!ELEMENT empleados (empleados+)>
    <!ELEMENT empleado (nombre, id, cargo, salario)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT cargo (#PCDATA)>
    <!ELEMENT salario (#PCDATA)>

=== nerenererr/dtd-practice/registro_empleados/externo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empleado SYSTEM "externo1.dtd">
<empleados>
    <empleado>
        <nombre>Terry</nombre>
        <id>1</id>
        <cargo>Ingeniero de Software</cargo>
        <salario>2700</salario>
    </empleado>
    <empleado>
        <nombre>Diego Alonso</nombre>
        <id>2</id>
        <cargo>Product Owner</cargo>
        <salario>2750</salario>
    </empleado>
    <empleado>
        <nombre>Amaia Ruiz</nombre>
        <id>3</id>
        <cargo>Dise√±adora UX</cargo>
        <salario>2200</salario>
    </empleado>        
</empleados>
